<a href="https://colab.research.google.com/github/sanlakshya/Python-Workbooks/blob/main/Pandas_ft_IMDB_Movie_Business_Case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas ft. IMDB Movie Business UseCase**

In [23]:
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
 # Exporting DataSet

Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 4.08MB/s]
Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 4.51MB/s]

In [24]:
import pandas as pd
movies=pd.read_csv('movies.csv',index_col=0)
movies.head()# Review DataSet

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [25]:
directors=pd.read_csv('directors.csv',index_col=0)
directors.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [27]:
data=movies.merge(directors,left_on='director_id',right_on='id',how='left')
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male

In [28]:
data.drop(['director_id','id_y'],axis=1,inplace=True)
data.head()#Removing the unnecessary columns ,both columns are same

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_x           1465 non-null   int64
 1   budget         1465 non-null   int64
 2   popularity     1465 non-null   int64
 3   revenue        1465 non-null   int64
 4   title          1465 non-null   object
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64
 7   year           1465 non-null   int64
 8   month          1465 non-null   object
 9   day            1465 non-null   object
 10  director_name  1465 non-null   object
 11  gender         1341 non-null   object
dtypes: float64(1), int64(6), object(5)
memory usage: 137.5+ KB

In [30]:
#Get movies data  with rating greater than equal to 7 along with title and director name details

In [31]:
data.loc[data['vote_average']>=7,['title','director_name']]

                                           title      director_name
0                                         Avatar      James Cameron
3                          The Dark Knight Rises  Christopher Nolan
8     Pirates of the Caribbean: Dead Man's Chest     Gore Verbinski
14     The Hobbit: The Battle of the Five Armies      Peter Jackson
16           The Hobbit: The Desolation of Smaug      Peter Jackson
...                                          ...                ...
1456                                  Eraserhead        David Lynch
1457                                  The Mighty      Peter Chelsom
1458                                          Pi   Darren Aronofsky
1460                              The Last Waltz    Martin Scorsese
1461                                      Clerks        Kevin Smith

[363 rows x 2 columns]

In [32]:
#High rated movies released after 2014

In [33]:
data.loc[(data['vote_average']>=7) & (data['year']>2014)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
30,43641,190000000,102,1506249360,Furious 7,7.3,4176,2015,Apr,Wednesday,James Wan,Male
78,43724,150000000,434,378858340,Mad Max: Fury Road,7.2,9427,2015,May,Wednesday,George Miller,Male
106,43773,135000000,100,532950503,The Revenant,7.3,6396,2015,Dec,Friday,Alejandro González Iñárritu,Male
162,43867,108000000,167,630161890,The Martian,7.6,7268,2015,Sep,Wednesday,Ridley Scott,Male
312,44128,75000000,48,108145109,The Man from U.N.C.L.E.,7.1,2265,2015,Aug,Thursday,Guy Ritchie,Male
394,44281,44000000,68,155760117,The Hateful Eight,7.6,4274,2015,Dec,Friday,Quentin Tarantino,Male
519,44538,50000000,42,69411370,13 Hours: The Secret Soldiers of Benghazi,7.0,938,2016,Jan,Wednesday,Michael Bay,Male
617,44757,40000000,68,320170008,The Conjuring 2,7.0,1949,2016,May,Friday,James Wan,Male
625,44770,35000000,53,194564672,The Intern,7.1,1881,2015,Sep,Thursday,Nancy Meyers,Female
635,44784,40000000,48,165478348,Bridge of Spies,7.2,2583,2015,Oct,Thursday,Steven Spielberg,Male
808,45194,30000000,65,91709827,Southpaw,7.3,2067,2015,Jun,Monday,Antoine Fuqua,Male
833,45293,28000000,61,201634991,Straight Outta Compton,7.7,1355,2015,Aug,Thursday,F. Gary Gray,Male
839,45301,28000000,57,133346506,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,Male
1344,47181,5000000,22,24804129,Race,7.1,478,2016,Feb,Friday,Stephen Hopkins,Male

In [34]:
data.shape

(1465, 12)

In [35]:
#Getting movies released on friday or sunday

In [38]:
data.loc[(data['day']=='Friday')| (data['day']=='Sunday')]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
22,43627,200000000,35,783766341,Spider-Man 2,6.7,4321,2004,Jun,Friday,Sam Raimi,Male
25,43632,150000000,21,836297228,Transformers: Revenge of the Fallen,6.0,3138,2009,Jun,Friday,Michael Bay,Male
53,43672,175000000,44,264218220,Waterworld,5.9,992,1995,Jul,Friday,Kevin Reynolds,NaN
61,43696,38000000,6,207283925,The Fast and the Furious,6.6,3428,2001,Jun,Friday,Rob Cohen,Male
65,43701,160000000,21,181674817,Poseidon,5.5,583,2006,May,Friday,Wolfgang Petersen,Male
...,...,...,...,...,...,...,...,...,...,...,...,...
1458,48335,60000,27,3221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,Male
1459,48359,0,2,0,George Washington,6.4,36,2000,Oct,Sunday,David Gordon Green,Male
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,Male
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,NaN

In [ ]:
#Converting Gender column into boolian column

In [39]:
def encode(data):
  if data=='Female':
    return 0
  else:
    return 1
data['gender']=data['gender'].apply(encode)
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,1
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,1
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,1

In [40]:
#creating a Profit Column from revenue and budget columns

In [41]:
def profit(data):
  return data['revenue']-data['budget']
data['profit']=data.apply(profit,axis=1)
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,1,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,1,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,1,632871626

In [42]:
#numbers of Movies released by director christopher noolan

In [52]:
int(data.loc[data['director_name'] == 'Christopher Nolan']['id_x'].count())

8

In [53]:
#Number of Movies directed by each directos

In [55]:
data['director_name'].value_counts()

director_name
Steven Spielberg       26
Martin Scorsese        19
Clint Eastwood         19
Woody Allen            18
Spike Lee              16
                       ..
Mike Leigh              5
Brad Anderson           5
Michael Polish          5
Darren Lynn Bousman     5
Nicole Holofcener       5
Name: count, Length: 199, dtype: int64

In [ ]:
#Finding all the movies average directed by each directors

In [56]:
data.groupby('director_name').ngroups#Unique groups present in the columns

199

In [59]:
data.groupby('director_name').groups

{'Adam McKay': [176, 323, 366, 505, 839, 916], 'Adam Shankman': [265, 300, 350, 404, 458, 843, 999, 1231], 'Alejandro González Iñárritu': [106, 749, 1015, 1034, 1077, 1405], 'Alex Proyas': [95, 159, 514, 671, 873], 'Alexander Payne': [793, 1006, 1101, 1211, 1281], 'Andrew Adamson': [11, 43, 328, 501, 947], 'Andrew Niccol': [533, 603, 701, 722, 1439], 'Andrzej Bartkowiak': [349, 549, 754, 911, 924], 'Andy Fickman': [517, 681, 909, 926, 973, 1023], 'Andy Tennant': [314, 320, 464, 593, 676, 885], 'Ang Lee': [99, 134, 748, 840, 1089, 1110, 1132, 1184], 'Anne Fletcher': [610, 650, 736, 789, 1206], 'Antoine Fuqua': [310, 338, 424, 467, 576, 808, 818, 1105], 'Atom Egoyan': [946, 1128, 1164, 1194, 1347, 1416], 'Barry Levinson': [313, 319, 471, 594, 878, 898, 1013, 1037, 1082, 1143, 1185, 1345, 1378], 'Barry Sonnenfeld': [13, 48, 90, 205, 591, 778, 783], 'Ben Stiller': [209, 212, 547, 562, 850], 'Bill Condon': [102, 307, 902, 1233, 1381], 'Bobby Farrelly': [352, 356, 481, 498, 624, 630, 654, 806, 928, 972, 1111], 'Brad Anderson': [1163, 1197, 1350, 1419, 1430], 'Brett Ratner': [24, 39, 188, 207, 238, 292, 405, 456, 920], 'Brian De Palma': [228, 255, 318, 439, 747, 905, 919, 1088, 1232, 1261, 1317, 1354], 'Brian Helgeland': [512, 607, 623, 742, 933], 'Brian Levant': [418, 449, 568, 761, 860, 1003], 'Brian Robbins': [416, 441, 669, 962, 988, 1115], 'Bryan Singer': [6, 32, 33, 44, 122, 216, 297, 1326], 'Cameron Crowe': [335, 434, 488, 503, 513, 698], 'Catherine Hardwicke': [602, 695, 724, 937, 1406, 1412], 'Chris Columbus': [117, 167, 204, 218, 229, 509, 656, 897, 996, 1086, 1129], 'Chris Weitz': [17, 500, 794, 869, 1202, 1267], 'Christopher Nolan': [3, 45, 58, 59, 74, 565, 641, 1341], 'Chuck Russell': [177, 410, 657, 1069, 1097, 1339], 'Clint Eastwood': [369, 426, 447, 482, 490, 520, 530, 535, 645, 727, 731, 786, 787, 899, 974, 986, 1167, 1190, 1313], 'Curtis Hanson': [494, 579, 606, 711, 733, 1057, 1310], 'Danny Boyle': [527, 668, 1083, 1085, 1126, 1168, 1287, 1385], 'Darren Aronofsky': [113, 751, 1187, 1328, 1363, 1458], 'Darren Lynn Bousman': [1241, 1243, 1283, 1338, 1440], 'David Ayer': [50, 273, 741, 1024, 1146, 1407], 'David Cronenberg': [541, 767, 994, 1055, 1254, 1268, 1334], 'David Fincher': [62, 213, 253, 383, 398, 478, 522, 555, 618, 785], 'David Gordon Green': [543, 862, 884, 927, 1376, 1418, 1432, 1459], 'David Koepp': [443, 644, 735, 1041, 1209], 'David Lynch': [583, 1161, 1264, 1340, 1456], 'David O. Russell': [422, 556, 609, 896, 982, 989, 1229, 1304], 'David R. Ellis': [582, 634, 756, 888, 934], 'David Zucker': [569, 619, 965, 1052, 1175], 'Dennis Dugan': [217, 260, 267, 293, 303, 718, 780, 977, 1247], 'Donald Petrie': [427, 507, 570, 649, 858, 894, 1106, 1331], 'Doug Liman': [52, 148, 251, 399, 544, 1318, 1451], 'Edward Zwick': [92, 182, 346, 566, 791, 819, 825], 'F. Gary Gray': [308, 402, 491, 523, 697, 833, 1272, 1380], 'Francis Ford Coppola': [487, 559, 622, 646, 772, 1076, 1155, 1253, 1312], 'Francis Lawrence': [63, 72, 109, 120, 679], 'Frank Coraci': [157, 249, 275, 451, 577, 599, 963], 'Frank Oz': [193, 355, 473, 580, 712, 813, 987], 'Garry Marshall': [329, 496, 528, 571, 784, 893, 1029, 1169], 'Gary Fleder': [518, 667, 689, 867, 981, 1165], 'Gary Winick': [258, 797, 798, 804, 1454], 'Gavin O'Connor': [820, 841, 939, 953, 1444], 'George A. Romero': [250, 1066, 1096, 1278, 1367, 1396], 'George Clooney': [343, 450, 831, 966, 1302], 'George Miller': [78, 103, 233, 287, 1250, 1403, 1450], 'Gore Verbinski': [1, 8, 9, 107, 119, 633, 1040], 'Guillermo del Toro': [35, 252, 419, 486, 1118], 'Gus Van Sant': [595, 1018, 1027, 1159, 1240, 1311, 1398], 'Guy Ritchie': [124, 215, 312, 1093, 1225, 1269, 1420], 'Harold Ramis': [425, 431, 558, 586, 788, 1137, 1166, 1325], 'Ivan Reitman': [274, 643, 816, 883, 910, 935, 1134, 1242], 'James Cameron': [0, 19, 170, 173, 344, 1100, 1320], 'James Ivory': [1125, 1152, 1180, 1291, 1293, 1390, 1397], 'James Mangold': [140, 141, 557, 560, 829, 845, 958, 1145], 'James Wan': [30, 617, 1002, 1047, 1337, 1417, 1424], 'Jan de Bont': [155, 224, 231, 270, 781], 'Jason Friedberg': [812, 1010, 1012, 1014, 1036], 'Jason Reitman': [792, 1092, 1213, 1295, 1299], 'Jaume Collet-Serra': [516, 540, 640, 725, 1011, 1189], 'Jay Roach': [195, 359, 389, 397, 461, 703, 859, 1072], 'Jean-Pierre Jeunet': [423, 485, 605, 664, 765], 'Joe Dante': [284, 525, 638, 1226, 1298, 1428], 'Joe Wright': [85, 432, 553, 803, 814, 855], 'Joel Coen': [428, 670, 691, 707, 721, 889, 906, 980, 1157, 1238, 1305], 'Joel Schumacher': [128, 184, 348, 484, 572, 614, 652, 764, 876, 886, 1108, 1230, 1280], 'John Carpenter': [537, 663, 686, 861, 938, 1028, 1080, 1102, 1329, 1371], 'John Glen': [601, 642, 801, 847, 864], 'John Landis': [524, 868, 1276, 1384, 1435], 'John Madden': [457, 882, 1020, 1249, 1257], 'John McTiernan': [127, 214, 244, 351, 534, 563, 648, 782, 838, 1074], 'John Singleton': [294, 489, 732, 796, 1120, 1173, 1316], 'John Whitesell': [499, 632, 763, 1119, 1148], 'John Woo': [131, 142, 264, 371, 420, 675, 1182], 'Jon Favreau': [46, 54, 55, 382, 759, 1346], 'Jon M. Chu': [100, 225, 810, 1099, 1186], 'Jon Turteltaub': [64, 180, 372, 480, 760, 846, 1171], 'Jonathan Demme': [277, 493, 1000, 1123, 1215], 'Jonathan Liebesman': [81, 143, 339, 1117, 1301], 'Judd Apatow': [321, 710, 717, 865, 881], 'Justin Lin': [38, 123, 246, 1437, 1447], 'Kenneth Branagh': [80, 197, 421, 879, 1094, 1277, 1288], 'Kenny Ortega': [412, 852, 1228, 1315, 1365], 'Kevin Reynolds': [53, 502, 639, 1019, 1059], ...}

In [61]:
data.groupby('director_name').get_group('Adam McKay')

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
176,43882,100000000,24,170432927,The Other Guys,6.1,1383,2010,Aug,Friday,Adam McKay,1,70432927
323,44151,72500000,12,162966177,Talladega Nights: The Ballad of Ricky Bobby,6.2,491,2006,Aug,Friday,Adam McKay,1,90466177
366,44236,65000000,22,128107642,Step Brothers,6.5,1062,2008,Jul,Friday,Adam McKay,1,63107642
505,44503,50000000,38,173649015,Anchorman 2: The Legend Continues,6.0,923,2013,Dec,Wednesday,Adam McKay,1,123649015
839,45301,28000000,57,133346506,The Big Short,7.3,2607,2015,Dec,Friday,Adam McKay,1,105346506
916,45443,26000000,29,90574188,Anchorman: The Legend of Ron Burgundy,6.7,1493,2004,Jul,Friday,Adam McKay,1,64574188

In [64]:
data.groupby('director_name')['id_x'].count().sort_values(ascending=False)#Number of movies directed by each directos

director_name
Steven Spielberg    26
Martin Scorsese     19
Clint Eastwood      19
Woody Allen         18
Robert Rodriguez    16
                    ..
Stephen Daldry       5
Tom Tykwer           5
Tim Hill             5
Uwe Boll             5
Wayne Wang           5
Name: id_x, Length: 199, dtype: int64

In [ ]:
#Finf Multiple Aggreation on Any Features/Columns

In [ ]:
#Directos released their first movie and last movie year

In [65]:
data.groupby('director_name')['year'].min()

director_name
Adam McKay                     2004
Adam Shankman                  2001
Alejandro González Iñárritu    2000
Alex Proyas                    1994
Alexander Payne                1999
                               ...
Wes Craven                     1984
Wolfgang Petersen              1981
Woody Allen                    1977
Zack Snyder                    2004
Zhang Yimou                    2002
Name: year, Length: 199, dtype: int64

In [68]:
data.groupby('director_name')['year'].aggregate(['min','max']).reset_index()

                   director_name   min   max
0                     Adam McKay  2004  2015
1                  Adam Shankman  2001  2012
2    Alejandro González Iñárritu  2000  2015
3                    Alex Proyas  1994  2016
4                Alexander Payne  1999  2013
..                           ...   ...   ...
194                   Wes Craven  1984  2011
195            Wolfgang Petersen  1981  2006
196                  Woody Allen  1977  2013
197                  Zack Snyder  2004  2016
198                  Zhang Yimou  2002  2014

[199 rows x 3 columns]

In [ ]:
#Getting Details movie by of the Highest Budgeted Directos

In [69]:
data['budget']=data['budget']/1000000

In [70]:
data['revenue']=data['revenue']/1000000

In [71]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237.0,150,2787.965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1,2550965087
1,43598,300.0,139,961.000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,1,661000000
2,43599,245.0,107,880.674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,1,635674609
3,43600,250.0,112,1084.939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1,834939099
4,43602,258.0,115,890.871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,1,632871626

In [74]:
data_dir_budget=data.groupby('director_name')['budget'].max().reset_index()
data_dir_budget

                   director_name  budget
0                     Adam McKay   100.0
1                  Adam Shankman    80.0
2    Alejandro González Iñárritu   135.0
3                    Alex Proyas   140.0
4                Alexander Payne    30.0
..                           ...     ...
194                   Wes Craven    40.0
195            Wolfgang Petersen   175.0
196                  Woody Allen    30.0
197                  Zack Snyder   250.0
198                  Zhang Yimou    94.0

[199 rows x 2 columns]

In [77]:
names=data_dir_budget.loc[data_dir_budget['budget']>=100,'director_name']
names

0                       Adam McKay
2      Alejandro González Iñárritu
3                      Alex Proyas
5                   Andrew Adamson
10                         Ang Lee
                  ...
187                    Tom Shadyac
188                     Tom Tykwer
189                     Tony Scott
195              Wolfgang Petersen
197                    Zack Snyder
Name: director_name, Length: 85, dtype: object

In [78]:
data.loc[data['director_name'].isin(names)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237.00,150,2787.965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1,2550965087
1,43598,300.00,139,961.000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,1,661000000
2,43599,245.00,107,880.674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,1,635674609
3,43600,250.00,112,1084.939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1,834939099
4,43602,258.00,115,890.871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,1,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,0.40,33,100.000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,1,99600000
1451,48268,0.20,13,4.505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,1,4305922
1452,48274,0.00,5,2.611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,1,2611555
1458,48335,0.06,27,3.221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,1,3161152
1460,48363,0.00,3,0.321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,1,321952

In [ ]:
#679 are the numbers of high budgeted movies

In [82]:
def func(x):
    return x['budget'].max() >= 100

data.groupby('director_name').filter(func)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237.00,150,2787.965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,1,2550965087
1,43598,300.00,139,961.000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,1,661000000
2,43599,245.00,107,880.674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,1,635674609
3,43600,250.00,112,1084.939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,1,834939099
4,43602,258.00,115,890.871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,1,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,0.40,33,100.000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,1,99600000
1451,48268,0.20,13,4.505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,1,4305922
1452,48274,0.00,5,2.611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,1,2611555
1458,48335,0.06,27,3.221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,1,3161152
1460,48363,0.00,3,0.321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,1,321952

In [ ]:
#Filter out the RISKY Movies

In [86]:
def func(x):
    x['risky'] = (x['budget'] - x['revenue'].mean()) >= 0
    return x

data_risky=data.groupby('director_name').apply(func)

/tmp/ipython-input-3566744326.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_risky=data.groupby('director_name').apply(func)

In [87]:
data_risky.loc[data_risky['risky']==True]

                          id_x  budget  popularity     revenue  \
director_name
Andrzej Bartkowiak 349   44192    60.0          29   55.987321
Atom Egoyan        946   45538    25.0           4    0.000000
                   1194  46370    15.0          26    8.459458
                   1347  47224     5.0           7    3.263585
Brett Ratner       24    43630   210.0           3  459.359555
...                        ...     ...         ...         ...
Uwe Boll           944   45536    25.0           7    2.405420
                   1058  45834    20.0           9   10.442808
                   1383  47453     3.5           4    0.000000
Wayne Wang         468   44419    55.0          19  154.906693
Zhang Yimou        192   43914    94.0          12   95.311434

                                               title  vote_average  \
director_name
Andrzej Bartkowiak 349                          Doom           5.0
Atom Egoyan        946          Where the Truth Lies           5.9
                   1194                        Chloe           5.9
                   1347          The Sweet Hereafter           6.8
Brett Ratner       24          X-Men: The Last Stand           6.3
...                                              ...           ...
Uwe Boll           944                    BloodRayne           3.5
                   1058            Alone in the Dark           3.1
                   1383  In the Name of the King III           3.3
Wayne Wang         468             Maid in Manhattan           5.6
Zhang Yimou        192            The Flowers of War           7.1

                         vote_count  year month        day  \
director_name
Andrzej Bartkowiak 349          609  2005   Oct   Thursday
Atom Egoyan        946           66  2005   Oct     Friday
                   1194         498  2009   Mar  Wednesday
                   1347         103  1997   May  Wednesday
Brett Ratner       24          3525  2006   May  Wednesday
...                             ...   ...   ...        ...
Uwe Boll           944          118  2005   Oct   Saturday
                   1058         173  2005   Jan     Friday
                   1383          19  2013   Dec     Friday
Wayne Wang         468          485  2002   Dec     Friday
Zhang Yimou        192          187  2011   Dec   Thursday

                              director_name  gender     profit  risky
director_name
Andrzej Bartkowiak 349   Andrzej Bartkowiak       1   -4012679   True
Atom Egoyan        946          Atom Egoyan       1  -25000000   True
                   1194         Atom Egoyan       1   -6540542   True
                   1347         Atom Egoyan       1   -1736415   True
Brett Ratner       24          Brett Ratner       1  249359555   True
...                                     ...     ...        ...    ...
Uwe Boll           944             Uwe Boll       1  -22594580   True
                   1058            Uwe Boll       1   -9557192   True
                   1383            Uwe Boll       1   -3500000   True
Wayne Wang         468           Wayne Wang       1   99906693   True
Zhang Yimou        192          Zhang Yimou       1    1311434   True

[131 rows x 14 columns]

In [ ]:
#Find the MOST Productive Movies

In [95]:
data_agg=data.groupby('director_name').agg({
    'year': ['min', 'max'],
    'title': 'count'
}).reset_index()
data_agg.head()
#MULTIPLE LEVEL INDEXING ACCESS

                 director_name  year       title
                                 min   max count
0                   Adam McKay  2004  2015     6
1                Adam Shankman  2001  2012     8
2  Alejandro González Iñárritu  2000  2015     6
3                  Alex Proyas  1994  2016     5
4              Alexander Payne  1999  2013     5

In [ ]:
#Multi to single level indexing

In [96]:
# Step 1: Aggregate
data_agg = data.groupby('director_name').agg({
    'year': ['min', 'max'],
    'title': 'count'
})

# Step 2: Flatten column names
data_agg.columns = ['year_min', 'year_max', 'title_count']

# Step 3: Reset index if needed (optional)
data_agg = data_agg.reset_index()

# Step 4: View the result
print(data_agg.head())

                 director_name  year_min  year_max  title_count
0                   Adam McKay      2004      2015            6
1                Adam Shankman      2001      2012            8
2  Alejandro González Iñárritu      2000      2015            6
3                  Alex Proyas      1994      2016            5
4              Alexander Payne      1999      2013            5